name: simple_ticket_widget
description: A simple ticket widget to display it vertically or horizontally.
version: 1.0.0
repository: https://github.com/hemantbeast/simple_ticket_widget

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
